version: '2'
services:
  myapp-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/myApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
